module: PromiseKit
custom_categories:
  - name: Core Components
    children:
      - Promise
      - Guarantee
      - Thenable
      - CatchMixin
      - Resolver
xcodebuild_arguments:
  - UseModernBuildSystem=NO
output:
  ../output
  # output directory is relative to config file… ugh
readme:
  Documents/README.md
theme:
  fullwidth
