branches:
  only:
    - master
    - v4
    - v7
    - legacy-1.x
    - /^\d+\.\d+\.\d+$/

stages:
  - name: pretest
  - name: test
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

os: osx
osx_image: xcode10.2
language: swift
xcode_project: PromiseKit.xcodeproj
xcode_scheme: PromiseKit-Package
xcode_destination: 'platform=macOS'

jobs:
  include:
    - stage: pretest
      name: Validate Linux test coverage
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - &test
      name: macOS
      stage: test
      install: swift package generate-xcodeproj --enable-code-coverage
      after_success: bash <(curl -s https://codecov.io/bash)
    - <<: *test
      name: iOS
      xcode_destination: 'OS=12.2,name=iPhone SE'
    - <<: *test
      name: tvOS
      xcode_destination: 'OS=12.2,name=Apple TV'

    - name: Linux
      env: SWIFT_VERSION='5.0-DEVELOPMENT-SNAPSHOT-2019-01-22-a'
      os: linux
      language: generic
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

    - name: JavaScript Promises/A+
      install: |
        bash -c "
          cd Tests/A+/JavaScript
          npm ci &>/dev/null
          npm run --hide-modules build"
      script: swift test --filter A__js.AllTests
      after_success: bash <(curl -s https://codecov.io/bash)
      cache.directories:
        - Tests/JS-A+/build
        - Tests/JS-A+/node_modules

    - stage: deploy
      before_script: |
        cat <<\ \ EOF> PromiseKit.podspec
        Pod::Spec.new do |s|
          s.name = "PromiseKit"
          s.source = { git: "https://github.com/mxcl/#{s.name}.git", tag: s.version }
          s.authors  = { 'Max Howell' => 'mxcl@me.com' }
          s.license = 'MIT'
          s.summary = 'Promises for Swift.'
          s.version = ENV["TRAVIS_TAG"]
          s.frameworks = 'Foundation'
          s.description = 'A thoughtful and complete implementation of promises for iOS, macOS, watchOS and tvOS.'
          s.requires_arc = true
          s.source_files = 'Sources/*.swift'
          s.swift_version = '5.0'
          s.social_media_url = 'https://twitter.com/mxcl'
          s.documentation_url = 'http://mxcl.dev/PromiseKit/reference/'
          s.ios.deployment_target = '8.0'
          s.osx.deployment_target = '10.10'
          s.tvos.deployment_target = '9.0'
          s.watchos.deployment_target = '2.0'
        end
        EOF
      script: pod trunk push --allow-warnings

    - name: Generate Documentation
      os: osx
      install: gem install jazzy
      script: |
        set -exo pipefail
        jazzy --config .github/jazzy.yml \
              --github_url "https://github.com/$TRAVIS_REPO_SLUG" \
              --module-version "$TRAVIS_TAG"
        git checkout gh-pages
        rm -rf reference/v7
        mv foo reference/v7
        git add reference/v7
        git config user.name  "Travis"
        git config user.email "jazzy@travis-ci.com"
        git commit -m "Updated docs for v$TRAVIS_TAG"
        git remote add secure-origin https://${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
        git push secure-origin gh-pages
