branches:
  only:
    - master
    - v4
    - v7
    - legacy-1.x
    - /^\d+\.\d+\.\d+$/
stages:
  - name: pretest
    if: type != push OR branch =~ /^\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: pretest
      name: Validate Linux has complete test coverage
      install: swift test --generate-linuxmain -Xswiftc -target -Xswiftc x86_64-apple-macosx10.12
      script: git diff --exit-code
      os: osx
      osx_image: xcode10.1
      language: swift
